# Tomcat 启动时提供的端口号
server:
  port: 19000

# 配置注册中心服务端
eureka:
  # 实例设置
  instance:
    # 服务端的实例名称
    hostname: localhost
  # 服务端设置
  server:
    # 关闭自我保护, 服务关闭后从列表中剔除, 默认true, 开启自我保护
    enable-self-preservation: true
    # 清理间隔(单位毫秒, 默认60*1000)
    eviction-interval-timer-in-ms: 60000
    # eureka server: 在运行期间会去统计心跳失败比例在15分钟之内是否低于85%
    renewal-percent-threshold: 0.85 # 默认0.85 指定自我保护机制的开启阈值
  # 客户端设置
  client:
    # 由于是注册中心服务端，所以设置为false，代表不向注册中心注册自己（注册中心集群时开启）
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #单机
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Spring 配置
spring:
  application:
    # 应用名称
    name: cloud-eureka

# 日志配置
logging:
  config: classpath:logback-spring.xml