spring:
  profiles:
    active: dev

mybatis-plus:
  # xml文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类的位置
  type-aliases-package: com.springcloud.demo.server.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-underline: true