server:
  port: 19001

spring:
  application:
    name: gateway
  cloud:
     gateway:
       discovery:
         locator:
           enable: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
       # 配置auth路由规则
       routes:
        # auth 模块
        - id: customer # 路由的ID，没有固定规则，但唯一要求，建议配合服务名
          uri: lb://auth #匹配后提供服务的路由地址-------这里用的动态路由格式统一为 lb://注册进eureka服务中心的名字
          predicates:
            - Path=/api/customer/** #断言，路径相匹配的进行路由--------断言也就是匹配方式，当识别到/api/customer/**时就会跳转上面的uri
          filters: #这个必须写
            - StripPrefix=1 # 忽略Path配置的个数，此处为1代表访问/api/customer/**时，会将api忽略，真实的访问地址为lb://auth/customer/**,如果为2，则为lb://auth/**
# 配置注册中心
# Eureka配置，服务注册到哪里
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:19000/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址