# Tomcat
server:
  port: 19003

# Spring
spring:
  application:
    # 应用名称
    name: auth
  profiles:
    # 环境配置
    active: dev
# 配置注册中心
# Eureka配置，服务注册到哪里
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:19000/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址