# Tomcat 启动时提供的端口号
server:
  port: 19003

# 配置注册中心,服务注册到哪里
eureka:
  # 客户端设置
  client:
    # 注册中心地址
    service-url:
      defaultZone: http://localhost:19000/eureka
  # 实例设置
  instance:
    # 服务的唯一ID
    instance-id: ${spring.application.name}:${server.port}
    # 注册服务时候可以使用IP地址
    prefer-ip-address: true

# Spring 配置
spring:
  application:
    # 应用名称
    name: auth-server
  datasource:
    druid:
      url: jdbc:mysql://192.168.100.10:3306/cloud-example?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: ~Yes1123~
      validation-query: SELECT 1 FROM DUAL

# mybatis plus配置
mybatis-plus:
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类路径
  type-aliases-package: com.example.common.data.dataobject
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-underline: true

management:
  #开启所有端点
  endpoints:
    # 开启所有监控端点
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    # 开启shutdown端口 调用关闭服务
    shutdown:
      enabled: true
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true

# 日志配置
logging:
  config: classpath:logback-spring.xml