# Tomcat 启动时提供的端口号
server:
  port: 19003

# 配置注册中心,服务注册到哪里
eureka:
  # 客户端设置
  client:
    # 注册中心地址
    service-url:
      defaultZone: http://localhost:19000/eureka
  # 实例设置
  instance:
    # 服务的唯一ID
    instance-id: ${spring.application.name}:${server.port}
    # 注册服务时候可以使用IP地址
    prefer-ip-address: true

# Spring 配置
spring:
  application:
    # 应用名称
    name: auth-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.10:3306/cloud-example?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ~Yes1123~
  jpa:
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
    database-platform: mysql
    hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口.默认为6379
    port: 6379
    password: 6666
    timeout: 15000ms
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000ms
        min-idle: 10

management:
  #开启所有端点
  endpoints:
    # 开启所有监控端点
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    # 开启shutdown端口 调用关闭服务
    shutdown:
      enabled: true
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true

# 日志配置
logging:
  config: classpath:logback-spring.xml