server:
  port: 19300

# 配置注册中心,服务注册到哪里
eureka:
  # 客户端设置
  client:
    # 注册中心地址
    service-url:
      defaultZone: http://localhost:19000/eureka
  # 实例设置
  instance:
    # 服务的唯一ID
    instance-id:  ${spring.application.name}:${server.port}
    # 注册服务时候可以使用IP地址
    prefer-ip-address: true

spring:
  application:
    # 应用名称
    name: server
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: DFF46C4173F616195D205C65A939726C
        #allow:
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 200
          merge-sql: true
        slf4j:
          enabled: true

redis:
  host: localhost
  port: 6379
  password:
  database: 11

jackson:
  time-zone: GMT+8

logging:
  level:
    com.example.server: debug
    #druid.sql: debug